# site settings
theme: jekyll-theme-slate
title: Rachael M. Cox
description: >
  Biochemistry PhD Candidate at the University of Texas at Austin<br>
  Center for Systems and Synthetic Biology
twitter_username: rachaelmcox
github_username: rachaelcox
